#!/bin/sh
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#
clear
echo 
echo "  Скрипт установки прошивки LEDE для MyBookLive Single"
echo "  ===================================================="
echo

. ./.fwver
FWKERN="mbl-lede-kernel.$KERN-ps$PAGESIZE-v$VERS.tar.gz"
FWROOTFS="mbl-lede-rootfs.$LEDEREL-v$VERS.tar.gz"
FWFILES="mbl-lede-files.v$VERS.tar.gz"
SDX="$HOME/mbl-disk-sdx"
CDIR="$PWD"

    echo
    echo -n  "----- Проверка доступности используемых утилит... "
    R=0
    for F in "sgdisk" "mke2fs" "lsblk"; do
	E=0
	IFSSAVE="$IFS"; IFS=":"
	for P in $PATH; do
	    if [ -x $P/$F ]; then
		E=1
		break
	    fi
	done
	IFS="$IFSSAVE"
	if [ $E = 0 ]; then
	    R=1
	    echo
	    echo "Необходимый исполняемый файл '$F' не найден."
	fi
    done
    [ $R = 1 ] && exit 1
    echo "OK"
    echo

    if [ ! -f ./$FWKERN -a -f ./$FWROOTFS -a -f ./$FWFILES ]; then
	echo
	echo Отсутствуют необходимые файлы прошивки
	echo
	exit 2
    fi
    echo
    echo  "  На следующем экране будет выведен список дисков в вашей системе"
    echo  "  Вам будет необходимо выбрать диск для установки прошивки MyBookLive-LEDE"
    echo
    read -p "  Нажмите ENTER для продолжения..." KEY
    clear
    echo
    echo

    LASTD=$(ls /dev/?d? -1 | cut -c6- | tail -n 1)
    lsblk -o NAME,TRAN,MODEL,SIZE,FSTYPE,LABEL
    echo 
    read -p "Введите имя диска для MyBookLive (например, sdb или sdc), по умолчанию $LASTD: " DISK
    echo
    [ "$DISK" = "" ] && DISK=$LASTD
    echo "ВНИМАНИЕ: Все существующие данные на диске /dev/${DISK} будут утеряны!"
    echo
    read -p  "Продолжить (y/n)? " KEY
    echo
    [ ! "$KEY" = "y" ] && exit 3

    echo "----- Создание таблицы разделов"

    # Оригинальная разметка WD
    # primary 528M  2576M
    # primary 2576M 4624M
    # primary 16M 528M
    # primary 4624M -1M

    sgdisk --zap-all /dev/${DISK} >/dev/null
    [ $? != 0 ] && exit 40
    echo

    echo "Создание раздела 1 (BOOT)... "
    sgdisk --new=1:1M:64M /dev/${DISK}
    [ $? != 0 ] && exit 41
    sgdisk -A 1:set:2 /dev/${DISK}                 # set the bit 2 attribute (legacy BIOS bootable) on partition 1

    echo
    echo "Создание раздела 2 (PROG)... "
    sgdisk --new=2:65M:4113M /dev/${DISK}
    [ $? != 0 ] && exit 42

    echo
    echo "Создание раздела 3 (SWAP)... "
    sgdisk --new=3:4114M:4623M /dev/${DISK} 
    [ $? != 0 ] && exit 43

    echo
    echo "Создание раздела 4 (DATA)... "
    sgdisk --new=4:4624M:-1M /dev/${DISK}
    [ $? != 0 ] && exit 44

    sync; sleep 1

    if [ ! -e ${DISK}1 -a -e ${DISK}2 -a -e ${DISK}3 -a -e ${DISK}4 ]; then
	echo
	echo "Ошибка создания таблицы разделов"
	echo
	exit 5
    fi

    echo
    echo "----- Форматирование разделов"
    echo

    dd if=/dev/zero of=/dev/${DISK}1 seek=0 bs=4096 count=2 2>/dev/null
    mke2fs -q -t ext2 -c -b 4096 -m 0 -L BOOT /dev/${DISK}1

    dd if=/dev/zero of=/dev/${DISK}2 seek=0 bs=4096 count=2 2>/dev/null
    mke2fs -q -t ext3 -b 4096 -m 5 -L PROG /dev/${DISK}2

    echo
    echo "----- Форматирование SWAP"
    echo

    dd if=/dev/zero of=/dev/${DISK}3 seek=0 bs=4096 count=2 2>/dev/null
    mkswap -L SWAP /dev/${DISK}3 >/dev/null

    # Prepare mount point
    [ ! -d $SDX ] && mkdir -p $SDX
    mount | grep $SDX >/dev/null && umount $SDX

    echo
    echo "----- Запись прошивки на диск: ROOTFS... "
    echo
    mount /dev/${DISK}2 $SDX
    [ $? != 0 ] && exit 6
    tar -zxf $FWROOTFS -C $SDX
    [ -f $SDX/bin/su ] && chmod 4555 $SDX/bin/busybox                     # set SUID for su to work properly
    [ -f $SDX/usr/bin/lua ] && chmod +s $SDX/usr/bin/lua                  # some lua fix
    [ -d $SDX/etc/lighttpd/conf.d ] && rm -f $SDX/etc/lighttpd/conf.d/*   # .conf here writes late
    umount $SDX

    echo
    echo "----- Запись прошивки на диск: KERNEL... "
    echo
    mount /dev/${DISK}1 $SDX
    tar -zxf $FWKERN -C $SDX boot
    [ -d $SDX/lost+found ] && rmdir $SDX/lost+found
    umount $SDX

    mount /dev/${DISK}2 $SDX
    tar -zxf $FWKERN -C $SDX lib
    tar -zxf $FWKERN -C $SDX etc
    umount $SDX

    echo
    echo "----- Запись прошивки на диск: CONFIG... "
    echo
    mount /dev/${DISK}2 $SDX
    tar -zxp --same-owner -f $FWFILES -C $SDX		# preserve permissions and ownersips
    umount $SDX

    echo
    echo "----- Создание раздела данных: DATA... "
    echo
    echo "      При первоначальной установке ответьте 'y'"
    echo "      Если раздел уже создавался ранее, и вы хотите"
    echo "      сохранить данные на нём, ответьте 'n'"
    echo
    read -p "      Создать раздел данных? (y/n)? " KEY
    if [ "$KEY" = "y" ]; then
        echo
        echo "----- Форматирование раздела данных... "
        echo

        dd if=/dev/zero of=/dev/${DISK}4 bs=4096 count=2 2>/dev/null
        mke2fs -q -t ext4 -b ${PAGESIZE} -m 0 -L DATA /dev/${DISK}4
        sync; sleep 1

	echo
        echo "----- Создание рабочих папок на разделе данных... "
        echo

        [ ! -d $SDX ] && mkdir $SDX
        mount /dev/${DISK}4 $SDX
        cd $SDX
	    mkdir -m 777 Public Media Download minidlna
	cd $SDX/Public
	    mkdir -m 777 watch-dir
	    cd watch-dir
	        mkdir -m 777 transmission rtorrent-load rtorrent-start
	cd $SDX/Download
	    mkdir -m 777 _incomplete
	cd $SDX/Media
	    ln -sr ../Download Download
	cd $CDIR
	umount $SDX
	sync; sleep 1
    fi
    echo
    echo Запись прошивки завершена. Таблица разделов диска ${DISK}:
    echo
    lsblk -o NAME,TRAN,MODEL,SIZE,FSTYPE,LABEL /dev/${DISK}
    echo
    sync; sleep 1

exit 0
